// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe_aMu7jsJltVO3Fp-UKYfHYrv8nCsmE8',
    appId: '1:484882107477:web:7f55e11b7cb4c20b9358dc',
    messagingSenderId: '484882107477',
    projectId: 'spotifycloneapp-f5c76',
    authDomain: 'spotifycloneapp-f5c76.firebaseapp.com',
    storageBucket: 'spotifycloneapp-f5c76.appspot.com',
    measurementId: 'G-4BR1VGW8PK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaqJguYH2r7J4z6IaZg_CzJFgBFIbAqyw',
    appId: '1:484882107477:android:a39d0ead37f4d0cb9358dc',
    messagingSenderId: '484882107477',
    projectId: 'spotifycloneapp-f5c76',
    storageBucket: 'spotifycloneapp-f5c76.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP9xoxjgTHiIwaULrZEdBJLUQdFHLR0FQ',
    appId: '1:484882107477:ios:e93313f985dc5f4b9358dc',
    messagingSenderId: '484882107477',
    projectId: 'spotifycloneapp-f5c76',
    storageBucket: 'spotifycloneapp-f5c76.appspot.com',
    iosBundleId: 'com.example.spotifycloneapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDP9xoxjgTHiIwaULrZEdBJLUQdFHLR0FQ',
    appId: '1:484882107477:ios:e93313f985dc5f4b9358dc',
    messagingSenderId: '484882107477',
    projectId: 'spotifycloneapp-f5c76',
    storageBucket: 'spotifycloneapp-f5c76.appspot.com',
    iosBundleId: 'com.example.spotifycloneapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCe_aMu7jsJltVO3Fp-UKYfHYrv8nCsmE8',
    appId: '1:484882107477:web:a111c832a19377009358dc',
    messagingSenderId: '484882107477',
    projectId: 'spotifycloneapp-f5c76',
    authDomain: 'spotifycloneapp-f5c76.firebaseapp.com',
    storageBucket: 'spotifycloneapp-f5c76.appspot.com',
    measurementId: 'G-6LHMJGS47C',
  );
}
